import { GoogleGenAI } from "@google/genai";
import { GroundingSource } from "../types";

export const sendMessageToGemini = async (
  prompt: string,
  history: { role: string; parts: { text: string }[] }[],
  countryContext?: string
): Promise<{ text: string; sources: GroundingSource[] }> => {
  
  // The API key is obtained exclusively from process.env.API_KEY as per coding guidelines.
  const apiKey = process.env.API_KEY;

  if (!apiKey) {
    console.error("API Key is missing. Make sure VITE_API_KEY is set in Vercel Environment Variables and redeploy.");
    return {
      text: "⚠️ **Configuration Error**\n\nThe API key is missing. If you are on Vercel, please ensure you have added `VITE_API_KEY` to your Environment Variables and **redeployed** the application (a simple refresh is not enough, you must trigger a new build).",
      sources: []
    };
  }
  
  // Initialize Gemini Client
  const ai = new GoogleGenAI({ apiKey: apiKey });

  try {
    // Map internal history to Gemini Content format
    const contents = history.map(msg => ({
      role: msg.role === 'user' ? 'user' : 'model',
      parts: msg.parts.map(p => ({ text: p.text }))
    }));

    // Append the current prompt
    contents.push({
      role: 'user',
      parts: [{ text: prompt }]
    });

    // Construct System Instruction based on context
    let systemInstruction = "You are the 'Crypto Regulations Guide', an elite AI compliance engine for Web3 institutions and founders. Your goal is to provide precise, up-to-date, and professional information regarding global crypto regulations (MiCA, SEC, VARA, MAS, etc.), anti-money laundering (AML) directives, and compliance risk factors. Always cite your sources when possible.";

    if (countryContext) {
      systemInstruction += `\n\nCRITICAL CONTEXT: You are currently acting as a specialized legal guide for **${countryContext}**. Focus your answers strictly on the regulatory framework, licensing requirements (e.g., SEC for USA, VARA for Dubai, MAS for Singapore), and compliance nuances specific to ${countryContext}. If the user asks a general question, frame your answer within the context of ${countryContext}'s laws.`;
    }

    // Switched to 'gemini-2.5-flash' for better stability and wider availability.
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: contents,
      config: {
        tools: [{ googleSearch: {} }],
        systemInstruction: systemInstruction,
      },
    });

    // Extract Text
    const text = response.text || "No content generated by the compliance engine.";

    // Extract Sources (Grounding)
    const sources: GroundingSource[] = [];
    
    // Check for grounding metadata
    const candidates = response.candidates;
    if (candidates && candidates[0] && candidates[0].groundingMetadata) {
      const chunks = candidates[0].groundingMetadata.groundingChunks;
      if (chunks) {
        chunks.forEach((chunk: any) => {
          if (chunk.web) {
            sources.push({
              title: chunk.web.title || "Regulatory Source",
              uri: chunk.web.uri
            });
          }
        });
      }
    }

    return { text, sources };

  } catch (error: any) {
    console.error("Gemini Service Error:", error);
    
    const errorMsg = error.message || String(error);

    return {
      text: `⚠️ **Compliance Engine Error**\n\nUnable to connect to the regulatory intelligence network.\n\n**Technical Details:** ${errorMsg}\n\nPlease ensure your API key is valid and has access to the \`gemini-2.5-flash\` model.`,
      sources: []
    };
  }
};